### ISSUE TITLE
update LibSFDropDown r33

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [Deahgib/PartyPlanner#2]
there is a bug in the bundled LibSFDropDown
```
1x ...ns/PartyPlanner/Libs/LibSFDropDown/LibSFDropDown.lua:1178: attempt to call upvalue 'GetMouseFocus' (a nil value)
[string "@PartyPlanner/Libs/LibSFDropDown/LibSFDropDown.lua"]:1178: in function <...ns/PartyPlanner/Libs/LibSFDropDown/LibSFDropDown.lua:1177>
[string "@PartyPlanner/Libs/LibSFDropDown/LibSFDropDown.lua"]:1189: in function <...ns/PartyPlanner/Libs/LibSFDropDown/LibSFDropDown.lua:1183>

Locals:
(*temporary) = nil
(*temporary) = "attempt to call upvalue 'GetMouseFocus' (a nil value)"
GetMouseFocus = nil
```
please update to the latest version https://github.com/sfmict/LibSFDropDown/releases/tag/r33

**Comment by Deahgib** [comment]
thank you for providing bug report AND the latest release version.

Please download a test build of the fix and install it in your wow addons folder from here:
https://github.com/Deahgib/PartyPlanner/blob/438e6bbbada2c8dae0de5ddfdb22b53e4bb930ca/dist/PartyPlanner-libsfdropdrown-r33-devupdate.zip

If the problem is fixed let me know and I can push the changes, I have no way of confirming as I have no sub

Thanks for the help!

**Comment by Alessandro-Barbieri** [comment]
ok, It worked

**Comment by Deahgib** [comment]
Hi @Alessandro-Barbieri  
thanks very much with your help resolving this! I couldn't have deployed a fix without it. :)
